name: 'Close issue when opened'
description: 'Closes a newly opened issue, tags it and puts it in the proper column in Smackore project board.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  ISSUE_URL:
    description: 'Issue URL'
    required: true
  ISSUE_NUMBER:
    description: 'Issue number'
    required: true
  REPOSITORY:
    description: 'Repository'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        gh label create closed-by-membrane-bot --description "Closed in GH action" --color AF7D7A || true
        gh issue edit $ISSUE_URL --add-project "Smackore" --add-label closed-by-membrane-bot
        export REPO_PATTERN=$(echo $REPOSITORY | sed 's|/|\\/|; s|^|/|; s|$|/|')
        export TICKET_ID="$(gh project item-list 19 --owner membraneframework --limit 100000 | awk -v num="$ISSUE_NUMBER" '{ numIdx = match($0, num); repoIdx = match($0, $REPO_PATTERN); if(numIdx && repoIdx) print $NF }')"
        gh issue close $ISSUE_URL --comment "Only PRs welcome ;)" --reason "not planned"
        sleep 10
        gh project item-edit --id "$TICKET_ID" --field-id PVTSSF_lADOAYE_z84AWEIBzgOGd1k --project-id PVT_kwDOAYE_z84AWEIB --single-select-option-id "fa223107"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        ISSUE_URL: ${{ inputs.ISSUE_URL }}
        ISSUE_NUMBER: ${{ inputs.ISSUE_NUMBER }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
      shell: bash
