name: Close issue when opened
on:
  issues:
    types:
      - opened
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          gh label create auto-closed-by-github-action --description "Closed in GH action" --color E99695
          gh issue close $ISSUE --comment "Only PRs welcome ;)" --reason "not planned"
          gh issue edit $ISSUE --add-project Smackore --add-label auto-closed-by-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.MEMBRANEFRAMEWORKADMIN_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}

