name: Close issue when opened
on:
  issues:
    types:
      - opened
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          # gh issue close $ISSUE_URL --comment "Only PRs welcome ;)" --reason "not planned"
          gh issue edit $ISSUE_URL --add-project "Smackore" --add-label auto-closed-by-github-action
          sleep 10

          echo "ALA MA KOTA $ISSUE_NUMBER"

        
          export TICKET_ID="$(gh project item-list 19 --owner membraneframework --limit 100000 | awk -v num="$ISSUE_NUMBER" '{ numIdx = match($0, num); repoIdx = match($0, /membraneframework\/github_actions_test/); if(numIdx && repoIdx) print $NF }')"
          echo "DUPA TICKET ID $TICKET_ID"
          echo $(gh project item-list 19 --owner membraneframework --limit 100000 | awk -v num="$ISSUE_NUMBER" '{ numIdx = match($0, num); repoIdx = match($0, /membraneframework\/github_actions_test/); if(numIdx && repoIdx) print $NF }')



          gh project item-edit --id "$TICKET_ID" --field-id PVTSSF_lADOAYE_z84AWEIBzgOGd1k --project-id PVT_kwDOAYE_z84AWEIB --text "fa223107"
        env:
          GITHUB_TOKEN: ${{ secrets.MEMBRANEFRAMEWORKADMIN_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}



