name: Close issue when opened
on:
  issues:
    types:
      - opened
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          gh issue close $ISSUE --comment "Only PRs welcome ;)" --reason "not planned"
          gh issue edit $ISSUE --add-project "Smackore" --add-label auto-closed-by-github-action
          gh project item-edit --id $ISSUE --field-id status --project-id 19 --text "New issues by community"
        env:
          GITHUB_TOKEN: ${{ secrets.MEMBRANEFRAMEWORKADMIN_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}

