name: Close issue when opened
on:
  issues:
    types:
      - opened
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          # gh issue close $ISSUE_URL --comment "Only PRs welcome ;)" --reason "not planned"
          gh issue edit $ISSUE_URL --add-project "Smackore" --add-label auto-closed-by-github-action

          export TICKET_ID="$(gh project item-list 19 --owner membraneframework | awk -v num="$ISSUE_ID" -v repo="$REPO" '{ numIdx = match($0, num); repoIdx = match($0, repo); if(numIdx && repoIdx) print $NF }')"
          echo "DUPA TICKET ID $TICKET_ID"



          # gh project item-edit --id "$(gh issue view --json id -t '{{.id}}' $ISSUE_URL)" --field-id PVTSSF_lADOAYE_z84AWEIBzgOGd1k --project-id PVT_kwDOAYE_z84AWEIB --text "fa223107"
        env:
          GITHUB_TOKEN: ${{ secrets.MEMBRANEFRAMEWORKADMIN_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_ID: ${{ github.event.issue.id }}
          REPO: ${{ github.repository }}



