name: 'Close issue when opened'
on:
  issues:
    types:
      - opened
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/close-issue
      with:
        GITHUB_TOKEN: ${{ secrets.MEMBRANEFRAMEWORKADMIN_TOKEN }}
        ISSUE_URL: ${{ github.event.issue.html_url }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        REPOSITORY: ${{ github.repository }}