name: Puts PR in a proper column in the Smackore project
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  move_to_proper_column:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          export PROJECT_NUMBER=19
          export PROJECT_ID=PVT_kwDOAYE_z84AWEIB
          export STATUS_FIELD_ID=PVTSSF_lADOAYE_z84AWEIBzgOGd1k
          export TARGET_COLUMN_ID=e6b1ee10
          
          export AUTHOR_ORIGIN=$(curl --request GET --url "https://api.github.com/orgs/membraneframework/members" --header "Authorization: Bearer $GITHUB_TOKEN" | python script.py $AUTHOR_LOGIN)

          if [ "$AUTHOR_ORIGIN" == "COMMUNITY" ]
          then
            gh pr edit --add-project Smackore
            sleep 10

            export TICKET_ID=$(gh project item-list $PROJECT_NUMBER --owner membraneframework --format json --limit 10000000 | python get_ticket_id.py "$PR_URL")
            gh project item-edit --id $TICKET_ID --field-id $STATUS_FIELD_ID --project-id $PROJECT_ID --single-select-option-id $TARGET_COLUMN_ID
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.MEMBRANEFRAMEWORKADMIN_TOKEN }}
          AUTHOR_LOGIN: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
